### ISSUE TITLE
Using Ecto.Adapters.SQL.Sandbox with savepoints

### ISSUE THREAD

**Issue by dougalcorn** [erlangbureau/jamdb_oracle#31]
I'm trying to run exunit tests against a test oracle database. Here's my `test.exs` config:

````elixir
{port, _} = Integer.parse(System.get_env("ORACLE_PORT"))
config :moble_ca, MobleCa.Repo,
  adapter: Ecto.Adapters.Jamdb.Oracle,
  database: System.get_env("ORACLE_PDB"),
  port: port,
  username: System.get_env("ORACLE_USR"),
  password: System.get_env("ORACLE_PWD"),
  hostname: "testdb",
  backoff_type: :exp,
  backoff_min: 20_000,
  pool: Ecto.Adapters.SQL.Sandbox
````

I ran my first test ok and it passed. I ran it again and it failed:

````
ORA-01086: savepoint 'TRAN' never established in this session or is invalid

15:52:40.267 [error] Jamdb.Oracle (#PID<0.262.0>) disconnected: ** (ErlangError) Erlang error: %{code: 1086, message: 'ORA-01086: savepoint \'TRAN\' never established in this session or is invalid\n'}
ORA-03137: TTC protocol internal error : [12209] [0] [] [] [] [] [] []
````

I think what's going on is my databases triggers conflict with using save points. My db schema is kind of inflexible. Is there a way to use the sandbox with a different strategy than savepoints?

**Comment by vstavskyi** [comment]
In Issues, there is similar one [Error using Repo.stream](https://github.com/erlangbureau/jamdb_oracle/issues/27).
Please post test code, I don't understand much from config only.

**Comment by dougalcorn** [comment]
I'm having a hard time understanding everything that's going on. My understanding (so far) is that the Ecto.Adapaters.SQL.Sandbox is what's wrapping my tests in transactions and rolling back on_exit.

I have a test that's inserting a user into the table. It uses `unsafe_validate_unique`:

````elixir
defmodule MobleCa.User do
  import Ecto.Changeset

  def changeset(user, params) do
    user
    |> cast(params, [:user_name, :password, :email_address, :drv_id, :forename, :surname, :user_type, :login_enabled, :id])
    |> unsafe_validate_unique(:user_name, MobleCa.Repo)
  end
````

I have a test setup like this:

````elixir
defmodule MobleCa.UserTest do
  use MobleCa.DataCase

  alias MobleCa.User

  describe "users" do

    # only drivers (Drv_ID)
    # only current allocations

    test "insert a driver" do
      initial_count = MobleCa.User.count
      nextval = Repo.nextval("WEB_USER_SEQ")
      changeset = MobleCa.User.changeset(%User{}, %{user_type: "DRIVER", login_enabled: "Y", user_name: "driver@example.com", password: "pass", drv_id: 123, id: nextval })
      assert %User{} = Repo.insert_or_update!(changeset)
      assert (initial_count + 1) == MobleCa.User.count
    end
````

The first time I run this test, it passes. However, when I connect to the test database I can see that my user is still in the database. When I run it a second time it fails like this:

````
root@089fcf13b24e:/app# mix test test/moble_ca/driver/user_test.exs:11
Including tags: [line: "11"]
Excluding tags: [:test]

11:39:54.447 [debug] QUERY OK source="web_user" db=10.1ms
SELECT count(w0.id) FROM web_ca.web_user w0 []
11:39:54.509 [debug] QUERY OK db=2.9ms
SELECT WEB_CA.WEB_USER_SEQ.nextval from dual []
11:39:54.610 [debug] QUERY OK source="web_user" db=1.1ms decode=0.1ms queue=0.1ms
SELECT NULL FROM web_ca.web_user w0 WHERE (w0.user_name = :1) AND (w0.id != :2) FETCH NEXT 1 ROWS ONLY ["driver@example.com", 8254]
ORA-01086: savepoint 'TRAN' never established in this session or is invalid

11:39:54.755 [error] Jamdb.Oracle (#PID<0.262.0>) disconnected: ** (ErlangError) Erlang error: %{code: 1086, message: 'ORA-01086: savepoint \'TRAN\' never established in this session or is invalid\n'}
ORA-03137: TTC protocol internal error : [12209] [0] [] [] [] [] [] []

  1) test users insert a driver (MobleCa.UserTest)
     test/moble_ca/driver/user_test.exs:11
     ** (Ecto.InvalidChangesetError) could not perform insert because changeset is invalid.
     
     Applied changes
     
         %{drv_id: 123, id: 8254, login_enabled: "Y", password: "pass",
           user_name: "driver@example.com", user_type: "DRIVER"}
     
     Params
     
         %{"drv_id" => 123, "id" => 8254, "login_enabled" => "Y", "password" => "pass",
           "user_name" => "driver@example.com", "user_type" => "DRIVER"}
     
     Errors
     
         %{user_name: [{"has already been taken",
             [validation: :unsafe_unique, fields: [:user_name]]}]}
     
     Changeset
     
         #Ecto.Changeset<action: :insert,
          changes: %{drv_id: 123, id: 8254, login_enabled: "Y", password: "pass",
            user_name: "driver@example.com", user_type: "DRIVER"},
          errors: [user_name: {"has already been taken",
            [validation: :unsafe_unique, fields: [:user_name]]}], data: #MobleCa.User<>,
          valid?: false>
     
     code: assert %User{} = Repo.insert_or_update!(changeset)
     stacktrace:
       (ecto) lib/ecto/repo/schema.ex:128: Ecto.Repo.Schema.insert!/4
       test/moble_ca/driver/user_test.exs:15: (test)



Finished in 0.7 seconds
7 tests, 1 failure, 6 skipped

Randomized with seed 525774
````

Because I'm calling `use MobleCa.DataCase` I think that means I'm doing a checkout for each test and setting the mode to shared. My understanding is that after the test, the Sandbox should be doing the rollback but it's not. I've disabled all the triggers on my database, so I don't think that's the problem. It just seems like the Jambdb.Oracle driver isn't properly implementing what the Ecto.Adapters.SQL.Sandbox expects.

**Comment by vstavskyi** [comment]
I couldn't reproduce the error.
Schema and changeset are defined in one module.
```
defmodule Jamdb.OracleTest.Erl do
  use Ecto.Schema
  import Ecto.Changeset
   
  @primary_key {:id, :integer, autogenerate: false}
  schema "erl4" do
    field :num, :float
    field :dat, :naive_datetime
    field :var2, :string
  end

  def changeset(value, params \\ %{}) do
    value
    |> cast(params, [:num, :id, :dat, :var2])
    |> unsafe_validate_unique(:var2, Jamdb.Oracle.TestRepo)
  end  
    
end

defmodule Jamdb.OracleTest do
  use ExUnit.Case
  import Ecto.Query
  alias Jamdb.Oracle.TestRepo
  alias Jamdb.OracleTest.Erl

  test "a" do
    changeset = Erl.changeset(%Erl{}, %{num: 300.0, id: 3, dat: nil, var2: "ABC" })
    assert %Erl{} = TestRepo.insert_or_update!(changeset)
  end

  test "b" do
    changeset = Erl.changeset(%Erl{}, %{num: 300.0, id: 3, dat: nil, var2: "GHJ" })
    assert %Erl{} = TestRepo.insert_or_update!(changeset)
  end

end

```
Table data:
```
100	1	2017-11-16 17:32:56	ABC
200	2	2017-11-16 17:33:15	DEF
```

```
16:02:06.420 [debug] QUERY OK source="erl4" db=2.1ms queue=1.3ms
SELECT NULL FROM erl4 e0 WHERE (e0.var2 = :1) AND (e0.id != :2) FETCH NEXT 1 ROWS ONLY ["ABC", 3]

16:02:06.431 [debug] QUERY OK source="erl4" db=0.3ms queue=1.0ms
SELECT NULL FROM erl4 e0 WHERE (e0.var2 = :1) AND (e0.id != :2) FETCH NEXT 1 ROWS ONLY ["GHJ", 3]

16:02:06.438 [debug] QUERY OK db=1.1ms
INSERT INTO erl4 (id,num,var2) VALUES (:1,:2,:3) [3, 300.0, "GHJ"]


  1) test a (Jamdb.OracleTest)
     test/test1.exs:26
     ** (Ecto.InvalidChangesetError) could not perform insert because changeset is invalid.
     
     Applied changes
     
         %{id: 3, num: 300.0, var2: "ABC"}
     
     Params
     
         %{"dat" => nil, "id" => 3, "num" => 300.0, "var2" => "ABC"}
     
     Errors
     
         %{var2: [{"has already been taken",
             [validation: :unsafe_unique, fields: [:var2]]}]}
     
     Changeset
     
         #Ecto.Changeset<action: :insert, changes: %{id: 3, num: 300.0, var2: "ABC"},
          errors: [var2: {"has already been taken",
            [validation: :unsafe_unique, fields: [:var2]]}],
          data: #Jamdb.OracleTest.Erl<>, valid?: false>
     
     stacktrace:
       (ecto) lib/ecto/repo/schema.ex:128: Ecto.Repo.Schema.insert!/4
       test/test1.exs:28: (test)

.

Finished in 0.1 seconds
2 tests, 1 failure

Randomized with seed 276995

```

**Comment by InteNs** [comment]
@vstavskyi here's a different use case with the same (reproducable) error:
```erlang
multi = Ecto.Multi.new
|> Ecto.Multi.insert(:user, %TestApp.User{})

TestApp.Repo.transaction(multi)
```

**Comment by vstavskyi** [comment]
autocommit  must be set to 0
` parameters: [autocommit: 0]`

Why do you need to insert empty row? 
By default Oracle does not return new ID. Maybe you already have a trigger.

**Comment by InteNs** [comment]
the empty row is just as an example, it doesn't matter what you do, this error is generated
I added the autocommit: 0 to the Repo config but that didn't change anything

in the following example you can see that when a rollback needs to happen it fails.
if the transaction doesn't have to roll back it works fine

Repo:
```erlang
config :plonquo_api, PlonquoApi.Repo,
  adapter: Ecto.Adapters.Jamdb.Oracle,
  username:   "TIMP",
  password:   "timp_password",
  database:   "XE",
  hostname:   "localhost",
  pool_size:  30,
  port:       1521,
  autocommit: 0
```
code:
```erlang
user = PlonquoApi.Accounts.get_user!(9995)
Ecto.Multi.new
 |> Ecto.Multi.update(:user, Ecto.Changeset.change(user))
 |> Ecto.Multi.run(:error, fn _ -> {:error, "error"} end)
 |> PlonquoApi.Repo.transaction
```
result:
```sh
[debug] QUERY OK db=543.3ms
begin []
ORA-01086: savepoint 'TRAN' never established in this session or is invalid

[debug] QUERY ERROR db=123.1ms
rollback []
** (ArgumentError) raise/1 expects a module name, string or exception as the first argument, got: %{code: 1086, message: 'ORA-01086: savepoint \'TRAN\' never established in this session or is invalid\n'}
    (db_connection) lib/db_connection.ex:794: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
```

**Comment by dougalcorn** [comment]
Basically, our practice now is to wrap all database operations in a transaction ourselves at the appropriate level. We have `autocommit: 0` and use savepoints:

````
MyApp.Repo.transaction(fn ->
 # do stuff
end, [mode: :savepoint, name: "myapp-unique-name"])
````

**Comment by vstavskyi** [comment]
@InteNs
try `parameters: [autocommit: 0]` instead of `autocommit: 0  `

**Comment by InteNs** [comment]
@vstavskyi thanks man, this worked for me.
unfortunately it created another problem, I do want autocommit for all the other database operations, it's just one module that needs transactions without autocommit.

should i create a seperate Repo with `autocommit: 0` for this usecase or is there a better solution?

**Comment by vstavskyi** [comment]
`Repo.query("COMOFF")`
Check one of my previous comments.
