### ISSUE TITLE
Ecto Schema construct (limit) doesn't seem to work!

### ISSUE THREAD

**Issue by collegeimprovements** [erlangbureau/jamdb_oracle#38]
```elixir
defmodule MyProject.Report do
  use Ecto.Schema

  # @primary_key false
  @primary_key {:ACT_ID, :id, autogenerate: true}
  schema "ACTIVITY_REPORT_2017" do
    field(:CONTACT_ID, :integer)
  end
end
```
And the following Queries work:
1. Raw Query
```elixir
Ecto.Adapters.SQL.query(MyProject.Repo, "SELECT * FROM ACTIVITY_REPORT_2017 where ROWNUM < 2")
```

2. `get` query
```elixir
Repo.get(Report, 113607038)
```
But when I try to run query with `limit`,  it doesn't work!!

```elixir
iex(1)> Report |> limit(10) |>  Repo.all
ORA-00933: SQL command not properly ended


14:50:51.444 [debug] QUERY ERROR source="ACTIVITY_REPORT_2017" db=198.9ms
SELECT C0.ACT_ID, C0.CONTACT_ID FROM ACTIVITY_REPORT_2017 C0 FETCH NEXT 10 ROWS ONLY []
** (DBConnection.ConnectionError) %{code: 933, message: 'ORA-00933: SQL command not properly ended\n'}
    (jamdb_oracle) lib/jamdb_oracle_ecto.ex:166: Ecto.Adapters.Jamdb.Oracle.Connection.error!/1
    (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:426: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
```

**Comment by vstavskyi** [comment]
Do you have row limiting example for 11g database?

**Comment by vstavskyi** [comment]
You want to use pseudocolumn ROWNUM in WHERE clause, but in ecto LIMIT clause is separated from WHERE clause.

**Comment by collegeimprovements** [comment]
Thanks a lot @vstavskyi, @arkadiyk :)
```elixir
query = from i in Item, where: fragment("ROWNUM < 101") #returns 100 rows
query |> Repo.all
```
