### ISSUE TITLE
Failed to connect on Amazon RDS for Oracle

### ISSUE THREAD

**Issue by enpedasi** [erlangbureau/jamdb_oracle#50]
I tried to connect to Amazon RDS for Oracle, Oracle 11g 11.2.0.4
Bellow error ocured.

As a basic knowledge,In Amazon RDS, DBA is not published to user.
```
[error] Jamdb.Oracle (#PID<0.573.0>) failed to connect: ** (ErlangError) Erlang error: {{:badmatch, {:error, :socket, :timeout, {:oraclient, #Port<0.17282>, :disconnected, 1, :select, 15000, <<224, 248, 202, 2, 125, 166, 50, 216, 231, 51, 106, 149, 169, 101, 231, 44>>, 15, 8192, :undefined, :undefined, :undefined, [], [timeout: 15000, password: 'TIGER', user: 'SCOTT', port: 1521, host: '---', service_name: '*****'], :utf8, #PID<0.575.0>}}}, [{:jamdb_oracle, :init, 1, [file: 'src/jamdb_oracle.erl', line: 35]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 365]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 333]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}
```

config/dev.exs
```
config :test, Test.Repo,
  adapter: Ecto.Adapters.Jamdb.Oracle,
  username: "SCOTT",
  password: "TIGER",
  database: "****",
  hostname: "hostaddr",
  port: 1521,
  pool_size: 3,
  timeout: 15000,
```

Server connections:
![image](https://user-images.githubusercontent.com/21321689/46410358-94f38380-c753-11e8-80a5-f48f398509e4.png)

`Schema` -> `OS User` shifted?

**Comment by vstavskyi** [comment]
Connection and Common Test have been successful. Wireshark dump [aws.zip](https://github.com/erlangbureau/jamdb_oracle/files/2442929/aws.zip)

Please post your dump.

![ws2](https://user-images.githubusercontent.com/23114643/46426815-51dfe300-c748-11e8-9e1d-206e27c2124a.png)
![ws](https://user-images.githubusercontent.com/23114643/46425858-82724d80-c745-11e8-920a-6165a26aeb71.png)
![aws](https://user-images.githubusercontent.com/23114643/46425605-c6b11e00-c744-11e8-9b10-2b35282cf8fe.png)

**Comment by enpedasi** [comment]
I rewrite the password, but  It was the same.
![image](https://user-images.githubusercontent.com/21321689/46474635-57a7f800-c81e-11e8-8479-f820e1b1f265.png)

**Comment by vstavskyi** [comment]
Small piece of dump will be very usefull.
Are there hex values after AUTH_PASSWORD and AUTH_SESSKEY in request packet?

**Comment by vstavskyi** [comment]
I've prepared [debug](https://github.com/erlangbureau/jamdb_oracle/tree/debug) branch. Authorization process is stopped after receiving from server AUTH_SESSKEY,AUTH_VFR_DATA,AUTH_PBKDF2_CSK_SALT values.

> {jamdb_oracle_conn,disconnect,
> [{error,debug,{debug,random,192,sess_key,48,auth_pass,32,auth_sess,48,speedy_key,0},
> {oraclient,
> 

To get this output, you can run Common Test with `rebar3 ct`, or repeat failed connection attempt.

**Comment by enpedasi** [comment]
A part of failed connections. (don't know how to test erl files)
```
Interactive Elixir (1.7.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> [error] GenServer #PID<0.510.0> terminating
** (FunctionClauseError) no function clause matching in :jamdb_oracle_conn.disconnect/2
    (jamdb_oracle) src/jamdb_oracle_conn.erl:63: :jamdb_oracle_conn.disconnect({:error, :debug, {:debug, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}, 0)
    (jamdb_oracle) src/jamdb_oracle_conn.erl:75: :jamdb_oracle_conn.reconnect/1
    (jamdb_oracle) src/jamdb_oracle.erl:51: :jamdb_oracle.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.507.0>): {:sql_query, {'SESSION', []}}
State: {:error, :debug, {:debug, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}
Client #PID<0.507.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (stdlib) gen_server.erl:210: :gen_server.call/3
    (jamdb_oracle) lib/jamdb_oracle.ex:74: Jamdb.Oracle.query/3
    (jamdb_oracle) lib/jamdb_oracle.ex:161: Jamdb.Oracle.checkout/1
    (db_connection) lib/db_connection/connection.ex:310: DBConnection.Connection.handle_cast/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
iex(1)> [error] GenServer #PID<0.511.0> terminating
** (FunctionClauseError) no function clause matching in :jamdb_oracle_conn.disconnect/2
    (jamdb_oracle) src/jamdb_oracle_conn.erl:63: :jamdb_oracle_conn.disconnect({:error, :debug, {:debug, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}, 0)
    (jamdb_oracle) src/jamdb_oracle_conn.erl:75: :jamdb_oracle_conn.reconnect/1
    (jamdb_oracle) src/jamdb_oracle.erl:51: :jamdb_oracle.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.508.0>): {:sql_query, {'SESSION', []}}
State: {:error, :debug, {:debug, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}
Client #PID<0.508.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (stdlib) gen_server.erl:210: :gen_server.call/3
    (jamdb_oracle) lib/jamdb_oracle.ex:74: Jamdb.Oracle.query/3
    (jamdb_oracle) lib/jamdb_oracle.ex:161: Jamdb.Oracle.checkout/1
    (db_connection) lib/db_connection/connection.ex:310: DBConnection.Connection.handle_cast/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
iex(1)> [error] GenServer #PID<0.529.0> terminating
** (FunctionClauseError) no function clause matching in :jamdb_oracle_conn.disconnect/2
    (jamdb_oracle) src/jamdb_oracle_conn.erl:63: :jamdb_oracle_conn.disconnect({:error, :debug, {:debug, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}, 0)
    (jamdb_oracle) src/jamdb_oracle_conn.erl:75: :jamdb_oracle_conn.reconnect/1
    (jamdb_oracle) src/jamdb_oracle.erl:51: :jamdb_oracle.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.528.0>): {:sql_query, {'SESSION', []}}
State: {:error, :debug, {:debug, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}
Client #PID<0.528.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (stdlib) gen_server.erl:210: :gen_server.call/3
    (jamdb_oracle) lib/jamdb_oracle.ex:74: Jamdb.Oracle.query/3
    (jamdb_oracle) lib/jamdb_oracle.ex:161: Jamdb.Oracle.checkout/1
    (db_connection) lib/db_connection/connection.ex:310: DBConnection.Connection.handle_cast/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
iex(1)> [error] GenServer #PID<0.527.0> terminating
** (FunctionClauseError) no function clause matching in :jamdb_oracle_conn.disconnect/2
    (jamdb_oracle) src/jamdb_oracle_conn.erl:63: :jamdb_oracle_conn.disconnect({:error, :debug, {:debug, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}, 0)
    (jamdb_oracle) src/jamdb_oracle_conn.erl:75: :jamdb_oracle_conn.reconnect/1
    (jamdb_oracle) src/jamdb_oracle.erl:51: :jamdb_oracle.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by vstavskyi** [comment]
{:debug, :random, **128**, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}
So, 128 key length means that aws rds was migrated to 11.2 from old version.
After clean installation 11.2 uses 192 key length, like in my example.
{debug,random,**192**,sess_key,48,auth_pass,32,auth_sess,48,speedy_key,0}

I need one more value, **verifierType** in jdbc. 
I'm going to fix debug branch soon and then I'm going to ask you to connect one more time.

Thank you for your patience.

**Comment by enpedasi** [comment]
Certainly this schema is a migration from 10 g.
Do not worry. I am enjoying it.

**Comment by vstavskyi** [comment]
Debug branch is ready.
Please post new result.

**Comment by enpedasi** [comment]
Interactive Elixir (1.7.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> {debug,2361,random,128,sess_key,48,auth_pass,32,auth_sess,48,speedy_key,0}
iex(1)> [error] GenServer #PID<0.384.0> terminating
** (FunctionClauseError) no function clause matching in :jamdb_oracle_conn.disconnect/2
    (jamdb_oracle) src/jamdb_oracle_conn.erl:63: :jamdb_oracle_conn.disconnect({:error, :debug, {:debug, 2361, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}, 0)
    (jamdb_oracle) src/jamdb_oracle_conn.erl:75: :jamdb_oracle_conn.reconnect/1
    (jamdb_oracle) src/jamdb_oracle.erl:51: :jamdb_oracle.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.381.0>): {:sql_query, {'SESSION', []}}
State: {:error, :debug, {:debug, 2361, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}
Client #PID<0.381.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (stdlib) gen_server.erl:210: :gen_server.call/3
    (jamdb_oracle) lib/jamdb_oracle.ex:74: Jamdb.Oracle.query/3
    (jamdb_oracle) lib/jamdb_oracle.ex:161: Jamdb.Oracle.checkout/1
    (db_connection) lib/db_connection/connection.ex:310: DBConnection.Connection.handle_cast/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
iex(1)> {debug,2361,random,128,sess_key,48,auth_pass,32,auth_sess,48,speedy_key,0}
iex(1)> [error] GenServer #PID<0.400.0> terminating
** (FunctionClauseError) no function clause matching in :jamdb_oracle_conn.disconnect/2
    (jamdb_oracle) src/jamdb_oracle_conn.erl:63: :jamdb_oracle_conn.disconnect({:error, :debug, {:debug, 2361, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}, 0)
    (jamdb_oracle) src/jamdb_oracle_conn.erl:75: :jamdb_oracle_conn.reconnect/1
    (jamdb_oracle) src/jamdb_oracle.erl:51: :jamdb_oracle.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.399.0>): {:sql_query, {'SESSION', []}}
State: {:error, :debug, {:debug, 2361, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}
Client #PID<0.399.0> is alive

**Comment by enpedasi** [comment]
```
Interactive Elixir (1.7.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> {debug,2361,random,128,sess_key,48,auth_pass,32,auth_sess,48,speedy_key,0}
iex(1)> [error] GenServer #PID<0.384.0> terminating
** (FunctionClauseError) no function clause matching in :jamdb_oracle_conn.disconnect/2
    (jamdb_oracle) src/jamdb_oracle_conn.erl:63: :jamdb_oracle_conn.disconnect({:error, :debug, {:debug, 2361, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}, 0)
    (jamdb_oracle) src/jamdb_oracle_conn.erl:75: :jamdb_oracle_conn.reconnect/1
    (jamdb_oracle) src/jamdb_oracle.erl:51: :jamdb_oracle.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.381.0>): {:sql_query, {'SESSION', []}}
State: {:error, :debug, {:debug, 2361, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}
Client #PID<0.381.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (stdlib) gen_server.erl:210: :gen_server.call/3
    (jamdb_oracle) lib/jamdb_oracle.ex:74: Jamdb.Oracle.query/3
    (jamdb_oracle) lib/jamdb_oracle.ex:161: Jamdb.Oracle.checkout/1
    (db_connection) lib/db_connection/connection.ex:310: DBConnection.Connection.handle_cast/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
iex(1)> {debug,2361,random,128,sess_key,48,auth_pass,32,auth_sess,48,speedy_key,0}
iex(1)> [error] GenServer #PID<0.400.0> terminating
** (FunctionClauseError) no function clause matching in :jamdb_oracle_conn.disconnect/2
    (jamdb_oracle) src/jamdb_oracle_conn.erl:63: :jamdb_oracle_conn.disconnect({:error, :debug, {:debug, 2361, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}, 0)
    (jamdb_oracle) src/jamdb_oracle_conn.erl:75: :jamdb_oracle_conn.reconnect/1
    (jamdb_oracle) src/jamdb_oracle.erl:51: :jamdb_oracle.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.399.0>): {:sql_query, {'SESSION', []}}
State: {:error, :debug, {:debug, 2361, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}
Client #PID<0.399.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    ...
    ...
```

**Comment by vstavskyi** [comment]
Thank you, this [commit](https://github.com/erlangbureau/jamdb_oracle/commit/9095b87515405b4c7e2a2961c992e2334af761d5) should work.

**Comment by enpedasi** [comment]
```
Interactive Elixir (1.7.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> {debug,2361,random,128,sess_key,48,auth_pass,32,auth_sess,48,speedy_key,0}
iex(1)> {debug,2361,random,128,sess_key,48,auth_pass,32,auth_sess,48,speedy_key,0}
iex(1)> [error] GenServer #PID<0.257.0> terminating
** (FunctionClauseError) no function clause matching in :jamdb_oracle_conn.disconnect/2
    (jamdb_oracle) src/jamdb_oracle_conn.erl:63: :jamdb_oracle_conn.disconnect({:error, :debug, {:debug, 2361, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}, 0)
    (jamdb_oracle) src/jamdb_oracle_conn.erl:75: :jamdb_oracle_conn.reconnect/1
    (jamdb_oracle) src/jamdb_oracle.erl:51: :jamdb_oracle.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.254.0>): {:sql_query, {'SESSION', []}}
State: {:error, :debug, {:debug, 2361, :random, 128, :sess_key, 48, :auth_pass, 32, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}
Client #PID<0.254.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (stdlib) gen_server.erl:210: :gen_server.call/3
    (jamdb_oracle) lib/jamdb_oracle.ex:74: Jamdb.Oracle.query/3
    (jamdb_oracle) lib/jamdb_oracle.ex:161: Jamdb.Oracle.checkout/1
    (db_connection) lib/db_connection/connection.ex:310: DBConnection.Connection.handle_cast/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
iex(1)> [error] GenServer #PID<0.258.0> terminating
```

**Comment by vstavskyi** [comment]
No, return back master branch in deps.

**Comment by enpedasi** [comment]
The connection was successful!
I greatly appreciate your long,long-term support.

Best regards sincerely.
