### ISSUE TITLE
Compatibility with oracle 18.3.0?

### ISSUE THREAD

**Issue by epilgrim** [erlangbureau/jamdb_oracle#64]
One of the databases I connect to is upgrading from version 11.2.0.4 to 18.3.0 (which is 12.2.0.2). 
I'm getting the following error when trying to establish a connection:
```
18:28:48.781 [error] Jamdb.Oracle (#PID<0.5227.0>) failed to connect: ** (DBConnection.ConnectionError) {:function_clause, [{:jamdb_oracle_conn, :get_result, [:undefined], [file: 'src/jamdb_oracle_conn.erl', line: 314]}, {:jamdb_oracle_conn, :handle_resp, 4, [file: 'src/jamdb_oracle_conn.erl', line: 279]}, {:jamdb_oracle, :init, 1, [file: 'src/jamdb_oracle.erl', line: 39]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}
```

The question is: is this version of oracle db supposed to work? i couldn't find any information about the versions that this library is supposed to work with.

BTW, we have been working with this library for the last 2 years, so thank you for it!!

**Comment by epilgrim** [comment]
trying it manually it gives:
```
iex(5)> :jamdb_oracle.start_link(opts)
{:error,
 {:function_clause,
  [
    {:jamdb_oracle_conn, :get_result, [:undefined],
     [file: 'src/jamdb_oracle_conn.erl', line: 314]},
    {:jamdb_oracle_conn, :handle_resp, 4,
     [file: 'src/jamdb_oracle_conn.erl', line: 279]},
    {:jamdb_oracle, :init, 1, [file: 'src/jamdb_oracle.erl', line: 39]},
    {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]},
    {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]},
    {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}
  ]}}
** (EXIT from #PID<0.422.0>) shell process exited with reason: an exception was raised:
    ** (FunctionClauseError) no function clause matching in :jamdb_oracle_conn.get_result/1
        (jamdb_oracle) src/jamdb_oracle_conn.erl:314: :jamdb_oracle_conn.get_result(:undefined)
        (jamdb_oracle) src/jamdb_oracle_conn.erl:279: :jamdb_oracle_conn.handle_resp/4
        (jamdb_oracle) src/jamdb_oracle.erl:39: :jamdb_oracle.init/1
        (stdlib) gen_server.erl:374: :gen_server.init_it/2
        (stdlib) gen_server.erl:342: :gen_server.init_it/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```
I'm using latest master (1d2b521350a5)

**Comment by vstavskyi** [comment]
Please use recently updated [debug](https://github.com/erlangbureau/jamdb_oracle/tree/debug) branch to get debug output and query from sys.user$ to get user's data.

`select name,password,spare4,spare3,spare9,spare10 from sys.user$ where name='STAT'`

I got this on 18c

`{debug,18453,256,der_salt,16,sess_key,32,auth_pass,32,auth_sess,32,speedy_key,80}`

`name|password|spare4|spare3|spare9|spare10`
`STAT|16C3A08933207F97|S:5AF2D9FA653056277B362EE75F6305194DD7A652CAD1438229D773D5EEEF;T:7A18B56A6AE57F808AB23F0466FC2564EA07E0B77B3C5F32EA19BD7374BA844B2A3A83DDBF72868D5A5E33FCFB945B5D5B33BECB8C87B5DCF281CEAD765DC8E4D4A5C53238665A5CC6CAC3C38D2601DB|16382|0|0`

migrated from 11g
`{debug,6949,192,der_salt,16,sess_key,32,auth_pass,32,auth_sess,32,speedy_key,0}`

`name|password|spare4|spare3|spare9|spare10`
`STAT|16C3A08933207F97|S:5EFC1A49EF9823D3A10D3D4F975DA76F83D3D4C542E35389768EF93E5D46|(null)|(null)|(null)`

migrated from 10g
`{debug,2361,128,der_salt,16,sess_key,32,auth_pass,32,auth_sess,32,speedy_key,0}`

`name|password|spare4|spare3|spare9|spare10`
`STAT|16C3A08933207F97|(null)|(null)|(null)|(null)`

With master branch connection is always successful.

**Comment by epilgrim** [comment]
With the debug branch, i cannot connect to db 11 nor 12. with master branch, i can connect only to 11

master branch, oracle 11: connection ok.

debug branch, oracle 11:
```
10:02:07.223 [error] GenServer #PID<0.519.0> terminating
** (FunctionClauseError) no function clause matching in :jamdb_oracle_conn.disconnect/2
    (jamdb_oracle) src/jamdb_oracle_conn.erl:63: :jamdb_oracle_conn.disconnect({:error, :debug, {:debug, 6949, 192, :der_salt, :undefined, :sess_key, 48, :auth_pass, 48, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}, 0)
    (jamdb_oracle) src/jamdb_oracle_conn.erl:75: :jamdb_oracle_conn.reconnect/1
    (jamdb_oracle) src/jamdb_oracle.erl:59: :jamdb_oracle.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.509.0>): {:sql_query, {'SESSION', []}}
State: {:error, :debug, {:debug, 6949, 192, :der_salt, :undefined, :sess_key, 48, :auth_pass, 48, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}
Client #PID<0.509.0> is alive

    (stdlib) gen.erl:167: :gen.do_call/4
    (stdlib) gen_server.erl:219: :gen_server.call/3
    (jamdb_oracle) lib/jamdb_oracle.ex:44: Jamdb.Oracle.query/3
    (jamdb_oracle) lib/jamdb_oracle.ex:207: Jamdb.Oracle.checkout/1
    (db_connection) lib/db_connection/connection.ex:191: DBConnection.Connection.handle_cast/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
```

debug branch, oracle 12:
```
10:02:07.223 [error] GenServer #PID<0.519.0> terminating
** (FunctionClauseError) no function clause matching in :jamdb_oracle_conn.disconnect/2
    (jamdb_oracle) src/jamdb_oracle_conn.erl:63: :jamdb_oracle_conn.disconnect({:error, :debug, {:debug, 6949, 192, :der_salt, :undefined, :sess_key, 48, :auth_pass, 48, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}, 0)
    (jamdb_oracle) src/jamdb_oracle_conn.erl:75: :jamdb_oracle_conn.reconnect/1
    (jamdb_oracle) src/jamdb_oracle.erl:59: :jamdb_oracle.handle_call/3
    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.509.0>): {:sql_query, {'SESSION', []}}
State: {:error, :debug, {:debug, 6949, 192, :der_salt, :undefined, :sess_key, 48, :auth_pass, 48, :auth_sess, 48, :speedy_key, 0}, {:oraclient, :undefined, :disconnected, 1, :select, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, :undefined, [], [], :undefined, :undefined}}
Client #PID<0.509.0> is alive

    (stdlib) gen.erl:167: :gen.do_call/4
    (stdlib) gen_server.erl:219: :gen_server.call/3
    (jamdb_oracle) lib/jamdb_oracle.ex:44: Jamdb.Oracle.query/3
    (jamdb_oracle) lib/jamdb_oracle.ex:207: Jamdb.Oracle.checkout/1
    (db_connection) lib/db_connection/connection.ex:191: DBConnection.Connection.handle_cast/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
{{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,48,auth_sess,48,
        speedy_key,0}}
```

As I cannot connect, i cannot run the query you are asking

**Comment by vstavskyi** [comment]
debug branch is used only for generating keys, not for connecting.  :)
Use master branch (or sqlplus) to query from sys.user$.

**Comment by epilgrim** [comment]
dang! sadly, I cannot query the sys.user$ table either, as I don't have enough privileges.
Anything else i can do?
If you totally need this, i'll try to contact my US colleagues and see if they can provide it for my user

**Comment by vstavskyi** [comment]
You post 11 and 12 debug ouput, but how about 18?

**Comment by epilgrim** [comment]
i think we are getting mixed with the versions. 
what i said is 12, is in fact 12.2.0.2. Oracle's new version scheme for that one is 18.3.0, which is, if i'm not wrong, 18c

I only have access to versions 11.2.0.4 and 12.2.0.2

**Comment by vstavskyi** [comment]
So, on 11.2.0.4 you got
{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,**48**,auth_sess,48,speedy_key,0}

But, on 11.2.0.2 and 11.2.0.3 I got
{debug,6949,192,der_salt,undefined,sess_key,48,auth_pass,**32**,auth_sess,48,speedy_key,0}

And,  on 11.2.0.4 connection is succesful, but on 12 is failed.
Please wait for solution.

**Comment by vstavskyi** [comment]
By the way, 
just change user password and correct spare values would be generated in sys.user$.

**Comment by epilgrim** [comment]
Whoahh, resetting the passord does the trick!!

Before the reset, the spare 3, 9 and 10 where null. After the password reset spare3 has value, and spares 9 and 10 are 0

Now I can connect once again!!
Thank you very much for your support!!!
