### ISSUE TITLE
conn vs. pid()

### ISSUE THREAD

**Issue by walter-weinmann** [erlangbureau/jamdb_oracle#74]
Documentation on https://hexdocs.pm/jamdb_oracle/Jamdb.Oracle.html#start_link/1

According to the documentation of `Jamdb.Oracle` the function `start_link `gives a `pid `over `{:ok, pid()} | error, any()` back. For the function `query(conn, sql, params \\ [])` a conn parameter is required. How can I close this gap.

**Comment by vstavskyi** [comment]
use pid or %Jamdb.Oracle in conn parameter

**Comment by walter-weinmann** [comment]
with `pid `I get the following:

```
** (EXIT from #PID<0.101.0>) an exception was raised:
    ** (RuntimeError) attempted to call GenServer #PID<0.103.0> but no handle_call/3 clause was provided
        (db_connection) lib/gen_server.ex:773: DBConnection.ConnectionPool.handle_call/3
        (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

17:25:00.645 [error] GenServer #PID<0.103.0> terminating
** (RuntimeError) attempted to call GenServer #PID<0.103.0> but no handle_call/3 clause was provided
    (db_connection) lib/gen_server.ex:773: DBConnection.ConnectionPool.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.101.0>): {:sql_query, {nil, []}}
State: {:busy, #Reference<0.863063241.2164654087.174608>, %{delay: 0, idle: #Reference<0.863063241.2164523015.174634>, idle_interval: 1000, interval: 1000, next: 297, poll: #Reference<0.863063241.2164523015.174633>, slow: false, target: 50}}
Client #PID<0.101.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (stdlib) gen_server.erl:210: :gen_server.call/3
    (jamdb_oracle) lib/jamdb_oracle.ex:44: Jamdb.Oracle.query/3
    (ora_bench) lib/ora_bench/ora_bench.ex:486: OraBench.run_trial/7
    (ora_bench) lib/ora_bench/ora_bench.ex:416: OraBench.run_benchmark/0
    (ora_bench) lib/ora_bench/cli.ex:8: OraBench.CLI.main/1
    (elixir) lib/kernel/cli.ex:121: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

and with `%Jamdb.Oracle` pretty much the same:

```
** (EXIT from #PID<0.101.0>) an exception was raised:
    ** (RuntimeError) attempted to call GenServer #PID<0.103.0> but no handle_call/3 clause was provided
        (db_connection) lib/gen_server.ex:773: DBConnection.ConnectionPool.handle_call/3
        (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

17:30:55.838 [error] GenServer #PID<0.103.0> terminating
** (RuntimeError) attempted to call GenServer #PID<0.103.0> but no handle_call/3 clause was provided
    (db_connection) lib/gen_server.ex:773: DBConnection.ConnectionPool.handle_call/3
    (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
    (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.101.0>): {:sql_query, {nil, []}}
State: {:busy, #Reference<0.1312505263.2971009025.216964>, %{delay: 0, idle: #Reference<0.1312505263.2970877953.216990>, idle_interval: 1000, interval: 1000, next: 328, poll: #Reference<0.1312505263.2970877953.216989>, slow: false, target: 50}}
Client #PID<0.101.0> is alive

    (stdlib) gen.erl:169: :gen.do_call/4
    (stdlib) gen_server.erl:210: :gen_server.call/3
    (jamdb_oracle) lib/jamdb_oracle.ex:44: Jamdb.Oracle.query/3
    (ora_bench) lib/ora_bench/ora_bench.ex:486: OraBench.run_trial/7
    (ora_bench) lib/ora_bench/ora_bench.ex:416: OraBench.run_benchmark/0
    (ora_bench) lib/ora_bench/cli.ex:8: OraBench.CLI.main/1
    (elixir) lib/kernel/cli.ex:121: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by vstavskyi** [comment]
Few data in errors. Please post your code.

Working Examples
```
defp config do
    [
  username: "scott",
  password: "tiger",
  hostname: "localhost",
  database: "xe",
  port: 1521,
  timeout: :infinity,
  pool_size: 1,
  idle_interval: 1000000,
  parameters: [autocommit: 1, fetch: 100, read_timeout: 200]
    ]
  end
```

```
{:ok, conn} = Jamdb.Oracle.start_link(config())
query = %Jamdb.Oracle.Query{statement: "SELECT * FROM dual WHERE 1>=:1"}
DBConnection.prepare_execute(conn, query, [1]) |> IO.inspect
DBConnection.close(conn, query)
```

```
{:ok, pool} = Jamdb.Oracle.start_link(config())
DBConnection.transaction(pool, fn conn ->
  query = %Jamdb.Oracle.Query{statement: "insert into erl3 (tim2) values(current_timestamp)"}
  query = DBConnection.prepare!(conn, query)
  try do
     DBConnection.execute!(conn, query, [])
  after
    DBConnection.close(conn, query)
  end
end)
```

```
 {:ok, conn} = Jamdb.Oracle.start_link(config())
  DBConnection.run(conn, fn conn ->
  query = %Jamdb.Oracle.Query{statement: "SELECT tim2 FROM erl3 WHERE num>:1"}
  DBConnection.execute!(conn, query, [0])  |> IO.inspect
  end)
```

```
 {:ok, conn} = Jamdb.Oracle.start_link(config())
  DBConnection.transaction(conn, fn conn ->
  query = %Jamdb.Oracle.Query{statement: "SELECT * FROM erl3 WHERE num>:1"}
  DBConnection.execute!(conn, query, [0])  |> IO.inspect
  end)
```

```
{:ok, conn} = Jamdb.Oracle.start_link(config())
  DBConnection.transaction(conn, fn conn ->
  DBConnection.rollback(conn, :oops)
  end)
```

```
{:ok, conn} = Jamdb.Oracle.start_link(config())
  DBConnection.transaction(conn, fn conn ->
  query = %Jamdb.Oracle.Query{statement: "SELECT * FROM erl3 WHERE num>:1"}
  stream = DBConnection.prepare_stream(conn, query, [0])
  Enum.to_list(stream)
  end)   |> IO.inspect
```

```
{:ok, pool} = Jamdb.Oracle.start_link(config())
  DBConnection.transaction(pool, fn conn ->
  query = %Jamdb.Oracle.Query{statement: "SELECT * FROM erl3 WHERE num>:1"}
  query = DBConnection.prepare!(conn, query)
  try do
    stream = DBConnection.stream(conn, query, [0])
    Enum.to_list(stream)    |> IO.inspect
  after
    DBConnection.close(conn, query)
  end
  end)
```

**Comment by vstavskyi** [comment]
[commit](https://github.com/erlangbureau/jamdb_oracle/commit/a605042476ff3de05a5c895f4443ad0a76e2db2f) and update batching example


```
 uuid = Enum.map(1..999, fn x -> [String.replace(Ecto.UUID.generate(),"-","")] end)
{:ok, pool} = Jamdb.Oracle.start_link(config())
DBConnection.transaction(pool, fn conn ->
  query = %Jamdb.Oracle.Query{statement: "insert into erl8 (uuid) values(:1)", batch: true}
  query = DBConnection.prepare!(conn, query)
  try do
     DBConnection.execute!(conn, query, uuid)
  after
    DBConnection.close(conn, query)
  end
end)   |> IO.inspect

```

**Comment by walter-weinmann** [comment]
The whole thing has improved a lot thanks to the code examples, but unfortunately there is still a problem that I can't explain.

Based on the following code excerpt:

```
    Logger.info("Start ==========> trial no. #{trial_number_current}")

    sql_create = %Jamdb.Oracle.Query{statement: config["sql.create"]}
    IO.inspect(sql_create, label: "sql_create")
    sql_drop = %Jamdb.Oracle.Query{statement: config["sql.drop"]}
    IO.inspect(sql_drop, label: "sql_drop")

    IO.inspect(connections, label: "connections")
    DBConnection.prepare_execute(connections[1], sql_create, [])
    |> IO.inspect()
```    
the following log results:

```
17:36:21.094 [info] Start ==========> trial no. 1
sql_create: %Jamdb.Oracle.Query{
  name: nil,
  statement: "BEGIN EXECUTE IMMEDIATE 'CREATE TABLE ora_bench_table (key VARCHAR2(32) PRIMARY KEY, data VARCHAR2(4000), no_partitions NUMBER DEFAULT 8, partition_key NUMBER(5)) PARTITION BY RANGE (partition_key) (PARTITION p00000 VALUES LESS THAN (1), PARTITION p00001 VALUES LESS THAN (2), PARTITION p00002 VALUES LESS THAN (3), PARTITION p00003 VALUES LESS THAN (4), PARTITION p00004 VALUES LESS THAN (5), PARTITION p00005 VALUES LESS THAN (6), PARTITION p00006 VALUES LESS THAN (7), PARTITION p00007 VALUES LESS THAN (8))'; EXECUTE IMMEDIATE 'CREATE TRIGGER ora_bench_table_before_insert BEFORE INSERT ON ora_bench_table FOR EACH ROW BEGIN :new.partition_key := MOD (ASCII (SUBSTR (:new.key, 1, 1)) * 256 + ASCII (SUBSTR (:new.key, 2, 1)), :new.no_partitions); END ora_bench_table_before_insert;'; END;"
}
sql_drop: %Jamdb.Oracle.Query{name: nil, statement: "DROP TABLE ora_bench_table"}
connections: %{1 => #PID<0.103.0>}
** (EXIT from #PID<0.101.0>) killed

```

**Comment by walter-weinmann** [comment]
Configuration:

```
benchmark.batch.size=256
benchmark.comment=n/a
benchmark.core.multiplier=0
benchmark.database=db_19_3_ee
benchmark.driver=n/a
benchmark.host.name=jfww-windows
benchmark.id=b14f99a2302ef6a5ee052e4f763d325f
benchmark.module=n/a
benchmark.number.cores=8
benchmark.number.partitions=8
benchmark.os=amd64 / Windows 10 / 10.0
benchmark.transaction.size=512
benchmark.trials=5
benchmark.user.name=Walter

connection.fetch.size=1024
connection.host=0.0.0.0
connection.password=regit
connection.port=1521
connection.service=orclpdb1
connection.string=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=127.0.0.1)(PORT=1521)))(CONNECT_DATA=(SERVER=dedicated)(SERVICE_NAME=xe)))
connection.user=scott

file.bulk.delimiter=;
file.bulk.header=key;data
file.bulk.length=80
file.bulk.name=priv/ora_bench_bulk_data.csv
file.bulk.size=100
file.configuration.name.cx_oracle.python=priv/properties/ora_bench_cx_oracle_python.ini
file.configuration.name.oranif.erlang=priv/properties/ora_bench_oranif_erlang.properties
file.configuration.name=priv/properties/ora_bench.properties
file.result.delimiter=\t
file.result.header=benchmark id;benchmark comment;host name;no. cores;os;user name;database;module;driver;trial no.;SQL statement;core multiplier;fetch size;transaction size;bulk length;bulk size;batch size;action;start day time;end day time;duration (sec);duration (ns)
file.result.name=priv/ora_bench_result.tsv

sql.create=BEGIN EXECUTE IMMEDIATE 'CREATE TABLE ora_bench_table (key VARCHAR2(32) PRIMARY KEY, data VARCHAR2(4000), no_partitions NUMBER DEFAULT 8, partition_key NUMBER(5)) PARTITION BY RANGE (partition_key) (PARTITION p00000 VALUES LESS THAN (1), PARTITION p00001 VALUES LESS THAN (2), PARTITION p00002 VALUES LESS THAN (3), PARTITION p00003 VALUES LESS THAN (4), PARTITION p00004 VALUES LESS THAN (5), PARTITION p00005 VALUES LESS THAN (6), PARTITION p00006 VALUES LESS THAN (7), PARTITION p00007 VALUES LESS THAN (8))'; EXECUTE IMMEDIATE 'CREATE TRIGGER ora_bench_table_before_insert BEFORE INSERT ON ora_bench_table FOR EACH ROW BEGIN :new.partition_key := MOD (ASCII (SUBSTR (:new.key, 1, 1)) * 256 + ASCII (SUBSTR (:new.key, 2, 1)), :new.no_partitions); END ora_bench_table_before_insert;'; END;
sql.drop=DROP TABLE ora_bench_table
sql.insert=INSERT INTO ora_bench_table (key, data) VALUES (:key, :data)
sql.select=SELECT key, data FROM ora_bench_table
```

Options:

```
  defp jamdb_oracle_config(config)  do
    [
      database: config["connection.service"],
      hostname: config["connection.host"],
      idle_interval: 1000000,
      parameters: [
        autocommit: false,
        fetch: String.to_integer(config["connection.fetch.size"])
      ],
      password: config["connection.password"],
      pool_size: case config["benchmark.core.multiplier"] do
        "0" -> String.to_integer(config["benchmark.number.partitions"])
        _ -> 1
      end,
      port: String.to_integer(config["connection.port"]),
      timeout: :infinity,
      username: config["connection.user"]
    ]
  end
```

and start_link:

```
  defp create_database_objects(config) do
    case config["benchmark.core.multiplier"] do
      "0" ->
        case Jamdb.Oracle.start_link(jamdb_oracle_config(config)) do
          {:ok, conn} ->
            Map.new([{1, conn}])
          _ = other_reason ->
            raise(
              "[Error in create_database_objects] Jamdb.Oracle.start_list: reason=#{
                other_reason
              }"
            )
        end
      _ ->
        Enum.reduce(
          1..String.to_integer(config["benchmark.number.partitions"]),
          %{},
          fn (i, connections) ->
            case Jamdb.Oracle.start_link(jamdb_oracle_config(config)) do
              {:ok, conn} -> Map.put(connections, i, conn)
              _ = other_reason ->
                raise(
                  "[Error in create_database_objects] Jamdb.Oracle.start_list: reason=#{
                    other_reason
                  }"
                )
            end
          end
        )
    end
  end
```

**Comment by vstavskyi** [comment]
I don't see any errors in the code. Btw, it's cool.
Did you try to create simple ecto application to verify that driver is capable of establishing connections with your version of database ?
Or this is the first attempt of using an unknown driver?

**Comment by vasumur** [comment]
By running the below example I see there is runtime error because of nil being passed as 3rd value to the insert.

** (DBConnection.ConnectionError) :function_clause
    (db_connection 2.4.2) lib/db_connection.ex:674: DBConnection.execute!/4

`
   %{pid: pool} = Ecto.Adapter.lookup_meta(Everest.Repo)

    uuid =
      Enum.map(1..999, fn _x ->
        [String.replace(Ecto.UUID.generate(), "-", ""), "hello", nil]
      end)

    Logger.info("uuid = #{inspect(uuid)}")

    DBConnection.transaction(pool, fn conn ->
      query = %Jamdb.Oracle.Query{
        statement: "insert into erl8 (uuid, title, x ) values (:1, :2, :3)",
        batch: true
      }

      query = DBConnection.prepare!(conn, query)

      try do
        DBConnection.execute!(conn, query, uuid)
      after
        DBConnection.close(conn, query)
      end
    end)
    |> IO.inspect()
`
